<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city</name>
   <tag></tag>
   <elementGuidId>2aa057d3-1b4b-4b50-8bfe-5d7b3226f5bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tdb-details-tile']//span[contains(@data-ng-bind,'city')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tdb-details-tile']//span[contains(@data-ng-bind,'city')]</value>
   </webElementProperties>
</WebElementEntity>
