<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>postcode</name>
   <tag></tag>
   <elementGuidId>886382a3-8ab7-480a-af6e-406432ee25d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tdb-details-tile']//span[contains(@data-ng-bind,'postCode')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tdb-details-tile']//span[contains(@data-ng-bind,'postCode')]</value>
   </webElementProperties>
</WebElementEntity>
