<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>street</name>
   <tag></tag>
   <elementGuidId>dca63a1c-f9e1-4455-b1f6-835d8ae7612c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tdb-details-tile']//span[contains(@data-ng-bind,'street')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tdb-details-tile']//span[contains(@data-ng-bind,'street')]</value>
   </webElementProperties>
</WebElementEntity>
