<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modelOverview_V_class</name>
   <tag></tag>
   <elementGuidId>686adcde-d68d-405f-8949-844f18eb125a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//tdb-vehicle-model-tile/div[@data-body-type='V-Klasse'])</value>
   </webElementProperties>
</WebElementEntity>
