<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>generic_dropdown_transmission</description>
   <name>dropdown_transmission_select_byIndex</name>
   <tag></tag>
   <elementGuidId>2693c7c2-d69d-4184-86e9-0e55aa03536c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//tdb-dropdown-box[contains(@selected-option,'transmission')]/ul/li)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//tdb-dropdown-box[contains(@selected-option,'transmission')]/ul/li)[1]</value>
   </webElementProperties>
</WebElementEntity>
