<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>generic_dropdown_fueltype</description>
   <name>dropdown_fueltype_select_byIndex</name>
   <tag></tag>
   <elementGuidId>1a331a94-21a7-4a05-9db9-9d00361607a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//tdb-dropdown-box[contains(@selected-option,'fuelType')]/ul/li)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//tdb-dropdown-box[contains(@selected-option,'fuelType')]/ul/li)[1]</value>
   </webElementProperties>
</WebElementEntity>
