<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>generic_dropdown_select_byIndex</name>
   <tag></tag>
   <elementGuidId>14d6b689-a053-4ff7-b0ac-b28b6ab7dcbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//ul[contains(@class,'open')]/li[@role='options'])[1]</value>
   </webElementProperties>
</WebElementEntity>
