<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>generic_dropdown_transmission</description>
   <name>generic_dropdown_transmission</name>
   <tag></tag>
   <elementGuidId>1af746a9-aa5d-40c8-9a3a-7398b2dd8aa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tdb-dropdown-box[contains(@selected-option,'transmission')]//button</value>
   </webElementProperties>
</WebElementEntity>
