<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>best_match</name>
   <tag></tag>
   <elementGuidId>76d4ac7a-fb5d-4926-8144-b254f758195e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'vehicle-carousel')]//div[contains(@class,'best-match')])[2]</value>
   </webElementProperties>
</WebElementEntity>
