<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continue_button_enabled</name>
   <tag></tag>
   <elementGuidId>4d3bd55a-18f5-425d-9798-a8eac3808d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[not(contains(@class,'disabled'))][@data-ng-click='ctrl.nextStep()']//span</value>
   </webElementProperties>
</WebElementEntity>
