<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>generic_timepicker_cell_byIndex</name>
   <tag></tag>
   <elementGuidId>88d79172-e32e-4730-bf02-edce6654a24b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='tdb-timepicker-cell'])[${index}]</value>
   </webElementProperties>
</WebElementEntity>
