<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>generic_vehicle_select_byIndex</name>
   <tag></tag>
   <elementGuidId>3806690a-9cbe-4714-8151-4d1f83ff0cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'vehicle-carousel')]//button/div[@class='tdb-can-be-selected'])[${index}]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'vehicle-carousel')]//button/div[@class='tdb-can-be-selected'])[${index}]
</value>
   </webElementProperties>
</WebElementEntity>
