<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>salutation</name>
   <tag></tag>
   <elementGuidId>db028fb1-8b82-4789-8c22-f9b44d608203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@name='mainContactForm']//label[contains(@for,'slt-${salut}')]</value>
   </webElementProperties>
</WebElementEntity>
