<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>street</name>
   <tag></tag>
   <elementGuidId>e6d9a9c3-2870-4aaf-b66b-940cdd943b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@name='mainContactForm']//input[@type='text'][@name='street']</value>
   </webElementProperties>
</WebElementEntity>
