<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>change_step1_in_step2</name>
   <tag></tag>
   <elementGuidId>ce12121e-24e0-4f71-9ed3-ba1bddf6c0fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@data-translate='TDB_STEPNAVIGATION_CHANGE']</value>
   </webElementProperties>
</WebElementEntity>
