<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>step3_inactive</name>
   <tag></tag>
   <elementGuidId>a13236a1-1ab6-4c19-b312-3738ffdffc06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[contains(@class,'navigation-step-inactive')]/a[@data-ui-sref='schedule']</value>
   </webElementProperties>
</WebElementEntity>
