<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Schaltgetriebe</name>
   <tag></tag>
   <elementGuidId>b3977aaa-b2a4-454d-a070-1fd924234a84</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tdb-dropdown-box-option ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>options</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!option.filtered</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-repeat</name>
      <type>Main</type>
      <value>option in ctrl.options track by $index</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'tdb-dropdown-box-option--selected': ctrl.selectedOption === option,
                          'tdb-dropdown-box-option--disabled': ctrl.isOptionDisabled(option)}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>ctrl.setOption(option)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>tdb-dropdown-box-option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
         Schaltgetriebe
      </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tdb-vehicle-model-tile-c-class-saloon&quot;)/div[@class=&quot;tdb-vehicle-model-tile-cta ng-scope&quot;]/div[@class=&quot;tdb-vehicle-model-tile-cta-section / tdb-dropdown&quot;]/div[@class=&quot;tdb-vehicle-model-tile-cta-section / tdb-dropdown&quot;]/tdb-dropdown-box[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;tdb-dropdown-box&quot;]/ul[@class=&quot;tdb-dropdown-box-list tdb-dropdown-box-list--open&quot;]/li[@class=&quot;tdb-dropdown-box-option ng-scope&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Daimler - Probefahrt - Mercede/iframe_tdb-cont</value>
   </webElementProperties>
</WebElementEntity>
