<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Motorisierung</name>
   <tag></tag>
   <elementGuidId>97a4c629-5f3e-4895-ab82-685b010deb5e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!ctrl.selectedOption</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-bind</name>
      <type>Main</type>
      <value>ctrl.label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Motorisierung</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tdb-vehicle-model-tile-c-class-saloon&quot;)/div[@class=&quot;tdb-vehicle-model-tile-cta ng-scope&quot;]/div[@class=&quot;tdb-vehicle-model-tile-cta-section / tdb-dropdown&quot;]/div[@class=&quot;tdb-vehicle-model-tile-cta-section / tdb-dropdown&quot;]/tdb-dropdown-box[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;tdb-dropdown-box&quot;]/button[@class=&quot;tdb-dropdown-box-toggle&quot;]/span[@class=&quot;ng-binding ng-scope&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Daimler - Probefahrt - Mercede/iframe_tdb-cont</value>
   </webElementProperties>
</WebElementEntity>
