<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_TestDrive_button</name>
   <tag></tag>
   <elementGuidId>6b175b74-7d3a-4f65-abc5-d9f3d69d1e1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[contains(@data-ng-click,'sendTestDrive')]/span)[last()]</value>
   </webElementProperties>
</WebElementEntity>
