<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>generic_dropdown_motor</description>
   <name>dropdown_motor_select_byIndex</name>
   <tag></tag>
   <elementGuidId>3cf2d630-4334-406a-adea-7af5a9258b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//tdb-dropdown-box[contains(@selected-option,'motorisation')]/ul/li)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//tdb-dropdown-box[contains(@selected-option,'motorisation')]/ul/li)[1]</value>
   </webElementProperties>
</WebElementEntity>
