<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>generic_dropdown_fueltype</description>
   <name>generic_dropdown_fueltype</name>
   <tag></tag>
   <elementGuidId>920126a1-2b66-4b38-8bb1-aca0399a41c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//tdb-dropdown-box[contains(@selected-option,'fuelType')]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tdb-dropdown-box[contains(@selected-option,'fuelType')]//button</value>
   </webElementProperties>
</WebElementEntity>
