<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detailsTile</name>
   <tag></tag>
   <elementGuidId>64dee321-4709-4b4b-9c4b-ce5a2fe7c4a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tdb-details-tile']//ul[contains(@class,'contact-list')]</value>
   </webElementProperties>
</WebElementEntity>
