<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>step4_active</name>
   <tag></tag>
   <elementGuidId>90ed4613-894a-4586-8ad4-93a90170ce4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[contains(@class,'navigation-step-active')]/a[@data-ui-sref='summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[contains(@class,'navigation-step-active')]/a[@data-ui-sref='summary']</value>
   </webElementProperties>
</WebElementEntity>
