<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vehicleCard_legal_Information</name>
   <tag></tag>
   <elementGuidId>f82a120e-7263-4d14-9902-fe0e6b69ea77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tdb-vehicle-card']//div[contains(@class,'legal')]</value>
   </webElementProperties>
</WebElementEntity>
