<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vehicleCard</name>
   <tag></tag>
   <elementGuidId>b5ecb307-294c-49a5-ad5a-0b40f50e9d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tdb-vehicle-card']//div[contains(@class,'tile-headline')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tdb-vehicle-card']//div[contains(@class,'content')]</value>
   </webElementProperties>
</WebElementEntity>
